version: '3.7'
services:
  mongodb:
    image: mongo:6.0.13-jammy
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: testdb
    volumes:
      - ./data:/data/db
  mariadb:
    image: mariadb:lts-jammy
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    volumes:
      - ./dataMaria:/var/lib/mysql
  api:
    build: api/.
    restart: on-failure
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    depends_on:
      - mongodb
      - mariadb