version: '3.7'
services:
  mongodb:
    image: mongo:6.0.13-jammy
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: testdb
    volumes:
      - ./data:/data/db
  mariadb:
    image: mariadb:lts-jammy
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: testdb
    # volumes:
    #   - ./dataMaria:/var/lib/mysql
  api_rest:
    build:
      context: ./api/
      dockerfile: dockerfile_rest
    restart: on-failure
    ports:
      - 5000:5000
    environment:
      - FLASK_RUN_PORT=5000
    depends_on:
      - mongodb
      - mariadb
  api_graphql:
    build:
      context: ./api/
      dockerfile: dockerfile_graphql
    restart: on-failure
    ports:
      - 5001:5001
    environment:
      - FLASK_RUN_PORT=5001
    depends_on:
      - mongodb
      - mariadb